require 'http'

url = 'https://api.stage-smartflow.com/ext/v3/en/users/profile'
api_token = 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ6Z0FNM2U4NFNYTW8wWUI0aW1XUmxWZkx2Yk1IRlp3bV83MzU1ak0wcTE0In0.eyJleHAiOjE3MjgzNjgxMTgsImlhdCI6MTcyODM2MDkxOCwianRpIjoiMTdhMzYzZGMtYzdhNC00NmI1LTgwZmQtM2I5MDEyMTdkMDNkIiwiaXNzIjoiaHR0cHM6Ly9tYWluLnN0YWdlLXNtYXJ0Zmxvdy5jb20vYXV0aC9yZWFsbXMvc21hcnRmbG93X2FwaSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIyZDEyYWQwNi1mYjk3LTQwOTMtOGZjZC0zOTIwN2M4NDBmNzYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJzbWFydGZsb3dfYXBpIiwic2Vzc2lvbl9zdGF0ZSI6ImU3YjZkNmY2LTQ3ZjYtNGJkZi1hMTE4LWEzMzJmOTY3NmJmZCIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1zbWFydGZsb3dfYXBpIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6ImU3YjZkNmY2LTQ3ZjYtNGJkZi1hMTE4LWEzMzJmOTY3NmJmZCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtaWxpbmRAdGhpbmtiaXouY28uaW4iLCJsb2NhbGUiOiJqYSIsImVtYWlsIjoibWlsaW5kQHRoaW5rYml6LmNvLmluIn0.YdxTu0e6DSfU5nrhabyWRmjIYA8LIaAttmLdOoY1LcvUUEBO4dDOVeygunXCe-g18649vTULF7CGGOhGjezHxmiNf451bNszrdrkIAzBZEvc05_kBRRantcgzugbhrecMYnSLA_gH5WLSdKHWQhvxPyWI0mxkt4fhEVr5VBm4e9HoED8mgBnksDMRS0-GxJlnXEbiAulF_F4ZMfWeX6xGnZbVuq4rRzdLM6Iu8r67slZ-KmzS13AoCLEbFdVnz4QJcAu5uM7qULLPXO9_X0iHMkpYnQq1pqQV1HgIBm9INaSw8jgLmfkFfFDibztlusAWWcDJUXs9FiQVqaSmcpy8A'
response = HTTP.headers('auth_token' => api_token).get(url)

case response.status
when 200
  puts "Success: #{response.to_s}"
when 404
  puts "Error 404: Resource not found."
when 500
  puts "Error 500: Internal Server Error. Please try again later."
else
  puts "Error: #{response.status} - #{response.body.to_s}"
end
